# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: checkstyle
        args:
          - --config=/path/to/checkstyle.xml
      - id: spotbugs
        args:
          - --max_heap_size=512m
          - --spotbugs-xml
      - id: junit-test-discovery
        args:
          - --pattern=**/*Test.java
      - id: black
        name: black-formatting
        language_version: python3.9
        entry: black
        files: \.(java)$
