repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
        -   prettier@2.7.1
        -   prettier-plugin-java@2.1.0
        args: ["--write"]
        files: \.java$

